### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by jksolbakken** [navikt/forebygge-sykefravaer#79]
Hei! Vi forsøker å forenkle bygging og adm av baseimagene våre, og ønsker derfor å kun tilby major-versjoner. Dere baserer dere nå på `12.18-alpine`. Vil det være et problem for dere å bytte til versjon `12` (eller evt oppgradere til 14)? Den vil jevnlig oppdateres fra det nyeste med samme versjon på Docker Hub.  12.18 vil ikke forsvinne, men den vil ikke lenger holdes oppdatert med sikkerhetspatcher.

**Comment by thomasdufourd** [comment]
Lukker denne etter at applikasjonen kjører på `navikt/node-express:14` imaget.
